### PR TITLE
Merged bot/bot_preprocessing.py from plum branch

### PR DESCRIPTION
**Pull request by WarClans612**

### CODE REVIEW

**Comment by Billy4195** [comment]
@WarClans612 Can you help to change the indent style from `TAB` to 4 spaces?
Ref: http://vim.wikia.com/wiki/Converting_tabs_to_spaces
Hint. Use `retab` to transform existed TAB to spaces.

**Comment by WarClans612** [comment]
@Billy4195 The indent style has been changed in the latest commit

**Comment by Billy4195** [comment]
@WarClans612 Good! Then you need to squash two commits into one commit
Ref: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by WarClans612** [comment]
@Billy4195 Finished squashing two commits

**Pull request merged**
